name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    uses: jamf-concepts/concept-workflows/.github/workflows/terraform/build.yaml@main

  publish:
    needs: build-internal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: dist
      - name: Run GoReleaser (publish only)
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          args: continue --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
